import React from 'react';
import { FileText, Download, CheckCircle2, AlertTriangle } from 'lucide-react';
import { AnalysisStats } from '../types';

interface AIReportProps {
  stats: AnalysisStats;
  topic: string;
}

export const AIReport: React.FC<AIReportProps> = ({ stats, topic }) => {
  // Determine text based on topic (Mock logic for demo purposes)
  // In a real app, this would be generated by the LLM based on the batch of tweets.
  const isEduTopic = topic.toLowerCase().includes('bac') || topic.toLowerCase().includes('exam') || topic.toLowerCase().includes('edu');
  
  const synthesisText = isEduTopic 
    ? "The public perception regarding the 2025 reforms is deeply divided but nuanced. While there is a clear appreciation for the modernization of the history and arts syllabi, this is overshadowed by significant anxiety concerning the new math curriculum. Students and parents alike express concerns about 'fairness' and 'preparedness', suggesting a disconnect between policy intent and classroom reality."
    : "The analyzed discourse reveals a complex landscape of user opinions. Positive sentiment is largely driven by specific product features or announcements, while negative sentiment coalesces around customer service experiences and reliability issues. The neutral content suggests a large portion of the audience is currently in an 'wait-and-see' mode regarding the recent changes.";

  const biasText = isEduTopic
    ? "The polarization score indicates a 'High Conflict' environment. The bias is heavily skewed against institutional planning, with terms like 'disaster', 'rigged', and 'fail' appearing frequently in negative clusters. Conversely, positive clusters are isolated to specific subjects (Arts/History), indicating that the controversy is not about the *idea* of reform, but its specific *implementation* in core subjects."
    : "We observe a distinct echo chamber effect in the negative feedback loops, particularly among long-term users. There is a notable absence of bridge-building narratives; users tend to be either strongly supportive advocates or vocal detractors. This binary distribution contributes to the elevated polarization score seen in the dashboard.";

  return (
    <div className="col-span-1 lg:col-span-2 bg-slate-900/50 backdrop-blur border border-slate-800 rounded-xl p-6 animate-slide-up">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8 border-b border-slate-800 pb-6">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <h3 className="text-xl font-bold text-white tracking-tight">AI Detailed Report</h3>
            <button className="px-3 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-bold border border-slate-700 flex items-center gap-2 transition-colors">
              <Download className="w-3 h-3" /> PDF
            </button>
          </div>
          <p className="text-slate-400 text-sm">Qualitative interpretation of {stats.total} analyzed data points.</p>
        </div>

        {/* Score Card */}
        <div className="bg-slate-950 rounded-lg border border-slate-800 p-4 flex items-center gap-4 min-w-[200px]">
          <div className="text-right flex-1">
            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Polarization Score</div>
            <div className={`text-2xl font-bold ${stats.polarizationScore > 50 ? 'text-red-400' : 'text-green-400'}`}>
              {Math.round(stats.polarizationScore)}/100
            </div>
            <div className="text-xs text-slate-400">
              {stats.polarizationScore > 70 ? 'High Conflict' : stats.polarizationScore > 30 ? 'Moderate Consensus' : 'High Consensus'}
            </div>
          </div>
        </div>
      </div>

      {/* Content Columns */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Synthesis Column */}
        <div>
          <h4 className="flex items-center gap-2 text-green-400 font-bold mb-4">
            <CheckCircle2 className="w-5 h-5" />
            Synthesis & Perception
          </h4>
          <p className="text-slate-300 text-sm leading-relaxed text-justify opacity-90">
            {synthesisText}
          </p>
        </div>

        {/* Bias Column */}
        <div>
          <h4 className="flex items-center gap-2 text-red-400 font-bold mb-4">
            <AlertTriangle className="w-5 h-5" />
            Bias & Controversies
          </h4>
          <p className="text-slate-300 text-sm leading-relaxed text-justify opacity-90">
            {biasText}
          </p>
        </div>

      </div>
    </div>
  );
};
